
spring:
  data:
    mongodb:
      # The URI is optional, it's all of these lines into one
      # uri: "mongodb://root:example@localhost:27017/dislinkt"
      authentication-database: admin # default, used to authenticate against the admin database
      username: root # docker-compose
      password: example # docker-compose
      database: dislinkt
      host: mongo # If running from a Docker container, use the service name, not localhost
      port: 27017 # default

server:
  port: 8700

grpc:
  client:
    user-service:
      address: 'static://user-service:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext