

version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  userservice:
      build: './microservices/userservice/'
      ports:
        - 8761:8761
        - 8762:9090
      hostname: user-service
  postservice:
      build: './microservices/postservice/'
      ports:
        - 8750:8750
      hostname: post-service
      volumes:
        - ${HOME}/.xws_images:/etc
  messageservice:
      build: './microservices/messageservice/'
      ports:
        - 8700:8700
      hostname: message-service
  jobofferservice:
      build: './microservices/jobofferservice/'
      ports: 
        - 8777:8777
      hostname: joboffer-service
